// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpTbtu6KFvVPvvP95vNJadIKi7PmJ2Vqc',
    appId: '1:242304846630:web:668d8456d93de57569cfe7',
    messagingSenderId: '242304846630',
    projectId: 'ecommerceapp-e663a',
    authDomain: 'ecommerceapp-e663a.firebaseapp.com',
    storageBucket: 'ecommerceapp-e663a.firebasestorage.app',
    measurementId: 'G-1EVW417CQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFTkEdTRMN_yoZH63qXkw7rfX1ZJI4Xi0',
    appId: '1:242304846630:android:4ddc9479bd02bed369cfe7',
    messagingSenderId: '242304846630',
    projectId: 'ecommerceapp-e663a',
    storageBucket: 'ecommerceapp-e663a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wuSGJ7J0W4HOPbqpT6BMvttvz8z2kus',
    appId: '1:242304846630:ios:bf8a386d736a216869cfe7',
    messagingSenderId: '242304846630',
    projectId: 'ecommerceapp-e663a',
    storageBucket: 'ecommerceapp-e663a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
